/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Pantallas;

import ConexionBD.ConexionBD;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class ActualizarInv extends javax.swing.JFrame {

    /**
     * Creates new form ActulizarInv
     */
    public ActualizarInv() {
        initComponents();
    }

    ActualizarInv(Object object, boolean b) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        atxtpro = new javax.swing.JTextField();
        atxtvuni = new javax.swing.JTextField();
        atxtuni = new javax.swing.JTextField();
        atxtcant = new javax.swing.JTextField();
        atxtrpro = new javax.swing.JTextField();
        atxtnom = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnaactualizar = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 24)); // NOI18N
        jLabel1.setText("Referencia del producto");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(350, 120, 276, 52);

        jLabel2.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 24)); // NOI18N
        jLabel2.setText("Nombre");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(350, 190, 146, 48);

        jLabel3.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 24)); // NOI18N
        jLabel3.setText("Cantidad");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(350, 250, 133, 44);

        jLabel4.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 24)); // NOI18N
        jLabel4.setText("Unidad");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(350, 310, 124, 40);

        jLabel5.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 24)); // NOI18N
        jLabel5.setText("Valor unitario");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(350, 370, 164, 48);

        jLabel6.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 24)); // NOI18N
        jLabel6.setText("Proveedor");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(350, 420, 151, 60);

        atxtpro.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        getContentPane().add(atxtpro);
        atxtpro.setBounds(700, 430, 211, 41);

        atxtvuni.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        atxtvuni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atxtvuniActionPerformed(evt);
            }
        });
        getContentPane().add(atxtvuni);
        atxtvuni.setBounds(700, 370, 211, 41);

        atxtuni.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        getContentPane().add(atxtuni);
        atxtuni.setBounds(700, 310, 211, 41);

        atxtcant.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        getContentPane().add(atxtcant);
        atxtcant.setBounds(700, 250, 211, 41);

        atxtrpro.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        getContentPane().add(atxtrpro);
        atxtrpro.setBounds(700, 130, 211, 41);

        atxtnom.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        getContentPane().add(atxtnom);
        atxtnom.setBounds(700, 190, 211, 41);

        jLabel7.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 48)); // NOI18N
        jLabel7.setText("Inventario");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(490, 30, 288, 56);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LOGOPEQUEÑO.png"))); // NOI18N
        getContentPane().add(jLabel8);
        jLabel8.setBounds(0, 0, 200, 200);

        btnaactualizar.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        btnaactualizar.setText("ACTUALIZAR PRODUCTO");
        btnaactualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaactualizarActionPerformed(evt);
            }
        });
        getContentPane().add(btnaactualizar);
        btnaactualizar.setBounds(530, 530, 300, 80);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Otromas.jpg"))); // NOI18N
        getContentPane().add(jLabel9);
        jLabel9.setBounds(0, 0, 1355, 700);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void atxtvuniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atxtvuniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_atxtvuniActionPerformed

    private void btnaactualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaactualizarActionPerformed
      try{
            ConexionBD Con= new ConexionBD();
            Con.getConexion();
            String refer = atxtrpro.getText();
            String nom = atxtnom.getText();
            String cant = atxtcant.getText();
            String uni = atxtuni.getText();
            String val = atxtvuni.getText();
            String pro = atxtpro.getText();
            String SQL = "UPDATE inventario SET "
                    + "'ReferenciaProducto='"+refer+"'NombreIngrediente='"+nom+"'Cantidad='"+cant+"',Unidad'"+uni+"',"
                    + "ValorUnitario='"+val+"',IdProveedor='"+pro+"'"
                    + "WHERE referencia='"+refer+"'";
            Con.sentencia.execute(SQL); 		
            JOptionPane.showMessageDialog(null,
		"¡Registro Actualizado con Éxito!");
            Con.DesconectarBD(); 
        } catch (SQLException ex) {
            Logger.getLogger(ActualizarInv.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnaactualizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ActualizarInv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ActualizarInv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ActualizarInv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ActualizarInv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ActualizarInv().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField atxtcant;
    public javax.swing.JTextField atxtnom;
    public javax.swing.JTextField atxtpro;
    public javax.swing.JTextField atxtrpro;
    public javax.swing.JTextField atxtuni;
    public javax.swing.JTextField atxtvuni;
    public javax.swing.JButton btnaactualizar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
