/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Pantallas;

import ConexionBD.ConexionBD;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class ActualizarPlat extends javax.swing.JFrame {

    /**
     * Creates new form ActualizarPlat
     */
    public ActualizarPlat() {
        initComponents();
    }

 
    ActualizarPlat(Object object, boolean b) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        atxtpor = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Categorias = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        atxtpre = new javax.swing.JTextField();
        atxtcat = new javax.swing.JTextField();
        atxtpla = new javax.swing.JTextField();
        atxtnom = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnactualizar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        atxtpor.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        getContentPane().add(atxtpor);
        atxtpor.setBounds(810, 260, 210, 50);

        jLabel1.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 24)); // NOI18N
        jLabel1.setText("N° Platillo");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(440, 130, 125, 42);

        jLabel2.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 24)); // NOI18N
        jLabel2.setText("Nombre");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(440, 190, 121, 48);

        Categorias.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 24)); // NOI18N
        Categorias.setText("Categoria");
        getContentPane().add(Categorias);
        Categorias.setBounds(440, 330, 137, 40);

        jLabel4.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 24)); // NOI18N
        jLabel4.setText("Porciones");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(440, 260, 120, 47);

        jLabel5.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 24)); // NOI18N
        jLabel5.setText("Precio");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(440, 400, 120, 40);

        atxtpre.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        getContentPane().add(atxtpre);
        atxtpre.setBounds(810, 400, 210, 50);

        atxtcat.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        getContentPane().add(atxtcat);
        atxtcat.setBounds(810, 330, 210, 47);

        atxtpla.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        atxtpla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atxtplaActionPerformed(evt);
            }
        });
        getContentPane().add(atxtpla);
        atxtpla.setBounds(810, 120, 210, 50);

        atxtnom.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        getContentPane().add(atxtnom);
        atxtnom.setBounds(810, 190, 210, 48);

        jLabel3.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 48)); // NOI18N
        jLabel3.setText("ACTUALIZAR PLATILLO");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(440, 40, 550, 46);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LOGOPEQUEÑO.png"))); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(0, 0, 240, 200);

        btnactualizar.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        btnactualizar.setText("ACTUALIZAR PLATILLO");
        btnactualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnactualizarActionPerformed(evt);
            }
        });
        getContentPane().add(btnactualizar);
        btnactualizar.setBounds(540, 520, 360, 90);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Otromas.jpg"))); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, -30, 1360, 700);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void atxtplaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atxtplaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_atxtplaActionPerformed

    private void btnactualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnactualizarActionPerformed
          try{
            ConexionBD Con= new ConexionBD();
            Con.getConexion();
            String nom = atxtnom.getText();
            String por = atxtpor.getText();
            String cat = atxtcat.getText();
            String pre = atxtpre.getText();
            
            String SQL = "UPDATE inventario SET "
                    + "'NombrePlatillo='"+nom+"'Porciones='"+por+"'Categoria='"+cat+"',PrecioPlatillo'"+pre+"'"
                    + "WHERE NombrePlatillo='"+nom+"'";
            Con.sentencia.execute(SQL); 		
            JOptionPane.showMessageDialog(null,
		"¡Registro Actualizado con Éxito!");
            Con.DesconectarBD(); 
        } catch (SQLException ex) {
            Logger.getLogger(ActualizarPlat.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnactualizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ActualizarPlat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ActualizarPlat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ActualizarPlat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ActualizarPlat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ActualizarPlat().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Categorias;
    public javax.swing.JTextField atxtcat;
    public javax.swing.JTextField atxtnom;
    public javax.swing.JTextField atxtpla;
    public javax.swing.JTextField atxtpor;
    public javax.swing.JTextField atxtpre;
    public javax.swing.JButton btnactualizar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
}
