/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Pantallas;

import ConexionBD.ConexionBD;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author SAINFONET28
 */
public class Comanda extends javax.swing.JFrame {

    /**
     * Creates new form Comanda
     */
    public Comanda() {
        initComponents();
        Crear_Modelo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablecom = new javax.swing.JTable();
        btnfacturar = new javax.swing.JButton();
        btnconsultar = new javax.swing.JButton();
        txtcom = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        jFormattedTextField1.setText("jFormattedTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 48)); // NOI18N
        jLabel1.setText("COMANDAS");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(570, 50, 290, 80);

        tablecom.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        tablecom.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Platillo o Bebida", "Cantidad", "Mesa"
            }
        ));
        jScrollPane1.setViewportView(tablecom);
        if (tablecom.getColumnModel().getColumnCount() > 0) {
            tablecom.getColumnModel().getColumn(2).setResizable(false);
        }

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(250, 310, 890, 270);

        btnfacturar.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        btnfacturar.setText("FACTURAR");
        btnfacturar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnfacturarActionPerformed(evt);
            }
        });
        getContentPane().add(btnfacturar);
        btnfacturar.setBounds(690, 150, 150, 80);

        btnconsultar.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        btnconsultar.setText("CONSULTAR");
        btnconsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnconsultarActionPerformed(evt);
            }
        });
        getContentPane().add(btnconsultar);
        btnconsultar.setBounds(910, 150, 150, 80);

        txtcom.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        txtcom.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "N° Comanda", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Berlin Sans FB Demi", 0, 18))); // NOI18N
        getContentPane().add(txtcom);
        txtcom.setBounds(270, 150, 230, 80);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LOGOPEQUEÑO.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 265, 200);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Otromas.jpg"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 0, 1355, 700);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnfacturarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnfacturarActionPerformed
        Factura obj = new Factura();
        obj.setVisible(true);    
        dispose();
    }//GEN-LAST:event_btnfacturarActionPerformed

    private void btnconsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnconsultarActionPerformed
      Consultar();
    }//GEN-LAST:event_btnconsultarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Comanda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Comanda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Comanda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Comanda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Comanda().setVisible(true);
            }
        });
    }
    DefaultTableModel modelo;
      private void Crear_Modelo() {
        try{
            modelo = (new DefaultTableModel(
                    null, new String[]{
                      "IdComandas", "IdPlatillo", "Cantidad",
                      "NumeroMesa"}) {
                     Class[] types = new Class[]{
                     java.lang.String.class,java.lang.String.class,
                     java.lang.String.class,java.lang.String.class,
                     java.lang.String.class,java.lang.String.class,
                     java.lang.String.class,java.lang.String.class,
                     java.lang.String.class,java.lang.String.class,
                    };
                    boolean[] canEdit = new boolean[]{
                        false, false, false, false
                    };
                    public Class getColumnClass(int columnIndex){
                        return types[columnIndex];
                    }
                    public boolean isCellEditable(int rowIndex, int colIndex){
                        return canEdit[colIndex];
                    }
            });
            tablecom.setModel(modelo);
            
            } catch (Exception e){
                JOptionPane.showMessageDialog(null, e.toString() + "Error");
                }
        }
      private void Consultar(){
          try{
            int i=0; Object ob[]=null;
            ConexionBD Con = new ConexionBD();
            Con.getConexion();
            String SQL = "SELECT * FROM comandas";
            Con.resultado = Con.sentencia.executeQuery(SQL);
            while (Con.resultado.next()){
                modelo.addRow(ob);
                modelo.setValueAt(Con.resultado.getString("IdComandas"), i, 0);
                modelo.setValueAt(Con.resultado.getString("IdPlatillo"), i, 1);
                modelo.setValueAt(Con.resultado.getString("Cantidad"), i, 2);
                modelo.setValueAt(Con.resultado.getString("NumeroMesa"), i, 3);
                i++;
            }
            Con.DesconectarBD();
        } catch (SQLException ex){
            Logger.getLogger(Comanda.class .getName()).log(Level.SEVERE, null, ex);
        }
      }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnconsultar;
    private javax.swing.JButton btnfacturar;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablecom;
    private javax.swing.JTextField txtcom;
    // End of variables declaration//GEN-END:variables
}
