/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Pantallas;

import ConexionBD.ConexionBD;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author SAINFONET27
 */
public class Factura extends javax.swing.JFrame {

    /**
     * Creates new form Factura
     */
    public Factura() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        txtnufa = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablefac = new javax.swing.JTable();
        cbme = new javax.swing.JComboBox<>();
        cbdomi = new javax.swing.JComboBox<>();
        btnguardar = new javax.swing.JButton();
        btnlimpiar = new javax.swing.JButton();
        txtpro = new javax.swing.JTextField();
        txtcan = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        txtven = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtim = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtsub = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtpag = new javax.swing.JTextField();
        btnconsultar = new javax.swing.JButton();
        btneliminar = new javax.swing.JButton();
        ELIMINAR = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 51, 51));
        setForeground(new java.awt.Color(146, 63, 90));
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 48)); // NOI18N
        jLabel2.setText("FACTURA");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(360, 30, 280, 90);

        txtnufa.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        txtnufa.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "N° Factura", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Berlin Sans FB Demi", 0, 18))); // NOI18N
        txtnufa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnufaActionPerformed(evt);
            }
        });
        getContentPane().add(txtnufa);
        txtnufa.setBounds(200, 160, 230, 70);

        tablefac.setFont(new java.awt.Font("Elephant", 0, 11)); // NOI18N
        tablefac.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "N° ", "Platillo", "Precio", "Unidad", "Subtotal"
            }
        ));
        jScrollPane2.setViewportView(tablefac);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(720, 40, 590, 280);

        cbme.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        cbme.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mesa 1", "Mesa 2", "Mesa 3", "Mesa 4" }));
        cbme.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "N° Mesa", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Berlin Sans FB Demi", 0, 18))); // NOI18N
        cbme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbmeActionPerformed(evt);
            }
        });
        getContentPane().add(cbme);
        cbme.setBounds(490, 250, 200, 70);

        cbdomi.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        cbdomi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Si", "No" }));
        cbdomi.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Domicilio", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Berlin Sans FB Demi", 0, 18))); // NOI18N
        cbdomi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbdomiActionPerformed(evt);
            }
        });
        getContentPane().add(cbdomi);
        cbdomi.setBounds(490, 160, 200, 70);

        btnguardar.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 24)); // NOI18N
        btnguardar.setText("GUARDAR");
        btnguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguardarActionPerformed(evt);
            }
        });
        getContentPane().add(btnguardar);
        btnguardar.setBounds(330, 470, 150, 60);

        btnlimpiar.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 24)); // NOI18N
        btnlimpiar.setText("LIMPIAR");
        btnlimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlimpiarActionPerformed(evt);
            }
        });
        getContentPane().add(btnlimpiar);
        btnlimpiar.setBounds(510, 470, 160, 60);

        txtpro.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        txtpro.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Propinas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Berlin Sans FB Demi", 0, 18))); // NOI18N
        txtpro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtproActionPerformed(evt);
            }
        });
        getContentPane().add(txtpro);
        txtpro.setBounds(490, 330, 200, 70);

        txtcan.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        txtcan.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cantidad Comprada", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Berlin Sans FB Demi", 0, 18))); // NOI18N
        txtcan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcanActionPerformed(evt);
            }
        });
        getContentPane().add(txtcan);
        txtcan.setBounds(200, 340, 230, 70);

        jButton3.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 24)); // NOI18N
        jButton3.setText("CLIENTE");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(130, 470, 180, 60);

        txtven.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        txtven.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nombre del vendedor", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Berlin Sans FB Demi", 0, 18))); // NOI18N
        getContentPane().add(txtven);
        txtven.setBounds(200, 250, 230, 70);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LOGOPEQUEÑO.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 210, 200);

        jLabel3.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 24)); // NOI18N
        jLabel3.setText("Impoconsumo");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(950, 380, 160, 40);
        getContentPane().add(txtim);
        txtim.setBounds(1130, 380, 190, 40);

        jLabel5.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 24)); // NOI18N
        jLabel5.setText("Subtotal");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(950, 440, 150, 28);
        getContentPane().add(txtsub);
        txtsub.setBounds(1130, 440, 190, 40);

        jLabel6.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 24)); // NOI18N
        jLabel6.setText("Valor a pagar");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(950, 500, 170, 40);
        getContentPane().add(txtpag);
        txtpag.setBounds(1130, 500, 190, 40);

        btnconsultar.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 24)); // NOI18N
        btnconsultar.setText("CONSULTAR");
        getContentPane().add(btnconsultar);
        btnconsultar.setBounds(720, 340, 180, 50);

        btneliminar.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 24)); // NOI18N
        btneliminar.setText("ELIMINAR");
        btneliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminarActionPerformed(evt);
            }
        });
        getContentPane().add(btneliminar);
        btneliminar.setBounds(720, 400, 180, 50);

        ELIMINAR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Otromas.jpg"))); // NOI18N
        getContentPane().add(ELIMINAR);
        ELIMINAR.setBounds(0, 0, 1355, 700);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtnufaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnufaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnufaActionPerformed

    private void cbmeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbmeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbmeActionPerformed

    private void btnguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguardarActionPerformed
         ConexionBD Con = new ConexionBD();
        Con.getConexion();
        String emp = txtven.getText();
        String can = txtcan.getText();
        String domi = cbdomi.getSelectedItem().toString();
        String me = cbme.getSelectedItem().toString();
        String pro = txtpro.getText();
        String im = txtim.getText();
        String sub = txtsub.getText();
        String pag = txtpag.getText();

        if (!emp.isEmpty()){
            if (!can.isEmpty()) {
                if (!domi.isEmpty()) {
                    if (!me.isEmpty()) {
                        if (!pro.isEmpty()) {
                            if (!im.isEmpty()) {
                                if (!sub.isEmpty()) {
                                    if (!pag.isEmpty()) {
                                      
                                try {
                                        String SQL = "INSERT INTO platillos"
                                                +"(NombrePlatillo,Porciones,Categoria,PrecioPlatillo)"
                                                +" VALUES "
                                                +"('"+emp+"','"+can+"','"+domi+"','"+me+"','"+pro+"','"+im+"','"+sub+"','"+pag+");";
                                        Con.sentencia.execute(SQL);
                                        JOptionPane.showMessageDialog(null, "¡Los datos fueron guardados con exito!");
                                    } catch (SQLException ex) {
                                        Logger.getLogger(Empleados.class.getName()).log(Level.SEVERE,null, ex);
                                    }
                                } else {
                                    JOptionPane.showMessageDialog(null, "Por favsr ingrese el valor pagar");
                                }
                            } else {
                                JOptionPane.showMessageDialog(null, "Por favor ingrese el subtotsl");
                            }
                        } else {
                            JOptionPane.showMessageDialog(null, "Por favor ingrese el valor del impoconsumo");
                        }
                    } else {
                        JOptionPane.showMessageDialog(null, "Por favor ingrese cuanto es la propina");
                    }
                }  else {
                    JOptionPane.showMessageDialog(null, "Por favor ingrese el numero de mesa");
                }
            } else {
                JOptionPane.showMessageDialog(null, "Por favor ingrese el id de los domicilios");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Por favor ingrese la cantidad de platillos");
        }
    } else {
        JOptionPane.showMessageDialog(null, "Por favor ingrese la identificacion del empleado");
    }
     Con.DesconectarBD();   
    }//GEN-LAST:event_btnguardarActionPerformed

    private void btnlimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlimpiarActionPerformed
  
    }//GEN-LAST:event_btnlimpiarActionPerformed

    private void txtproActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtproActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtproActionPerformed

    private void txtcanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcanActionPerformed

    private void cbdomiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbdomiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbdomiActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btneliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminarActionPerformed
        
    try{
        String num = tablefac.getValueAt(tablefac.getSelectedRow(), 0) .toString();
        ConexionBD Con = new ConexionBD();
        Con.getConexion();
        String SQL = "DELETE FROM factura WHERE Id_Factura='"+num+"'";
        Con.sentencia.execute(SQL);
        JOptionPane.showMessageDialog(null, "¡El registro fué eliminado!");
        Con.DesconectarBD();
        } catch (SQLException ex) {
	Logger.getLogger(Factura.class.getName()).log(Level.SEVERE, null, ex);
        }
    
    }//GEN-LAST:event_btneliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Factura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Factura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Factura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Factura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Factura().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ELIMINAR;
    private javax.swing.JButton btnconsultar;
    private javax.swing.JButton btneliminar;
    private javax.swing.JButton btnguardar;
    private javax.swing.JButton btnlimpiar;
    private javax.swing.JComboBox<String> cbdomi;
    private javax.swing.JComboBox<String> cbme;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tablefac;
    private javax.swing.JTextField txtcan;
    private javax.swing.JTextField txtim;
    private javax.swing.JTextField txtnufa;
    private javax.swing.JTextField txtpag;
    private javax.swing.JTextField txtpro;
    private javax.swing.JTextField txtsub;
    private javax.swing.JTextField txtven;
    // End of variables declaration//GEN-END:variables
}
