/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Pantallas;

/**
 *
 * @author User
 */
public class Logincaj extends javax.swing.JFrame {

    /**
     * Creates new form Logincaj
     */
    public Logincaj() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btndom = new javax.swing.JButton();
        btnfac = new javax.swing.JButton();
        btnlog = new javax.swing.JButton();
        btnres = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LOGOPEQUEÑO.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 212, 200);

        jLabel2.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 48)); // NOI18N
        jLabel2.setText("BIENVENIDO CAJERO ");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(450, 50, 528, 122);

        btndom.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        btndom.setText("Domicilios");
        btndom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndomActionPerformed(evt);
            }
        });
        getContentPane().add(btndom);
        btndom.setBounds(700, 280, 460, 102);

        btnfac.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        btnfac.setText("Facturar");
        btnfac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnfacActionPerformed(evt);
            }
        });
        getContentPane().add(btnfac);
        btnfac.setBounds(120, 280, 460, 102);

        btnlog.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        btnlog.setText("Cerrar sesion");
        btnlog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlogActionPerformed(evt);
            }
        });
        getContentPane().add(btnlog);
        btnlog.setBounds(700, 460, 460, 102);

        btnres.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        btnres.setText("Reservaciones");
        btnres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnresActionPerformed(evt);
            }
        });
        getContentPane().add(btnres);
        btnres.setBounds(120, 460, 460, 100);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Otromas.jpg"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 0, 1355, 700);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnlogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlogActionPerformed
        Login obj = new Login();
        obj.setVisible(true);    
        dispose();
    }//GEN-LAST:event_btnlogActionPerformed

    private void btnfacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnfacActionPerformed
        Factura obj = new Factura();
        obj.setVisible(true);    
        dispose();
    }//GEN-LAST:event_btnfacActionPerformed

    private void btnresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnresActionPerformed
        Reservaciones obj = new Reservaciones();
        obj.setVisible(true);    
        dispose();
    }//GEN-LAST:event_btnresActionPerformed

    private void btndomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndomActionPerformed
        Domicilios obj = new Domicilios();
        obj.setVisible(true);    
        dispose();
    }//GEN-LAST:event_btndomActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Logincaj.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Logincaj.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Logincaj.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Logincaj.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Logincaj().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btndom;
    private javax.swing.JButton btnfac;
    private javax.swing.JButton btnlog;
    private javax.swing.JButton btnres;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
