/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Pantallas;

/**
 *
 * @author User
 */
public class Loginecomp extends javax.swing.JFrame {

    /**
     * Creates new form Loginecomp
     */
    public Loginecomp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnvinv = new javax.swing.JButton();
        btnainv = new javax.swing.JButton();
        btnpro = new javax.swing.JButton();
        btnpla = new javax.swing.JButton();
        btnlog = new javax.swing.JButton();
        btnrec = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LOGOPEQUEÑO.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 229, 200);

        jLabel2.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 48)); // NOI18N
        jLabel2.setText("BIENVENIDO ENCARGADO ");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(440, 50, 606, 70);

        jLabel3.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 48)); // NOI18N
        jLabel3.setText("DE COMPRAS");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(590, 120, 302, 55);

        btnvinv.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        btnvinv.setText("Visualizar inventario");
        btnvinv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnvinvActionPerformed(evt);
            }
        });
        getContentPane().add(btnvinv);
        btnvinv.setBounds(240, 430, 312, 81);

        btnainv.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        btnainv.setText("Agregar al inventario");
        btnainv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnainvActionPerformed(evt);
            }
        });
        getContentPane().add(btnainv);
        btnainv.setBounds(240, 290, 312, 81);

        btnpro.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        btnpro.setText("Proveedores");
        btnpro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnproActionPerformed(evt);
            }
        });
        getContentPane().add(btnpro);
        btnpro.setBounds(240, 570, 312, 81);

        btnpla.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        btnpla.setText("Platillos");
        btnpla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnplaActionPerformed(evt);
            }
        });
        getContentPane().add(btnpla);
        btnpla.setBounds(810, 290, 312, 81);

        btnlog.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        btnlog.setText("Cerrar sesion");
        btnlog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlogActionPerformed(evt);
            }
        });
        getContentPane().add(btnlog);
        btnlog.setBounds(810, 570, 312, 81);

        btnrec.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        btnrec.setText("Receta");
        btnrec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrecActionPerformed(evt);
            }
        });
        getContentPane().add(btnrec);
        btnrec.setBounds(810, 430, 312, 81);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Otromas.jpg"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 0, 1355, 700);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnproActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnproActionPerformed
        Proveedores obj = new Proveedores();
        obj.setVisible(true);    
        dispose();
    }//GEN-LAST:event_btnproActionPerformed

    private void btnplaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnplaActionPerformed
        Platillos obj = new Platillos();
        obj.setVisible(true);    
        dispose();
    }//GEN-LAST:event_btnplaActionPerformed

    private void btnrecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrecActionPerformed
        Receta obj = new Receta();
        obj.setVisible(true);    
        dispose();
    }//GEN-LAST:event_btnrecActionPerformed

    private void btnainvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnainvActionPerformed
        Inventario obj = new Inventario();
        obj.setVisible(true);    
        dispose();
    }//GEN-LAST:event_btnainvActionPerformed

    private void btnvinvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnvinvActionPerformed
        Inventario2 obj = new Inventario2();
        obj.setVisible(true);    
        dispose();
    }//GEN-LAST:event_btnvinvActionPerformed

    private void btnlogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlogActionPerformed
        Login obj = new Login();
        obj.setVisible(true);    
        dispose();
    }//GEN-LAST:event_btnlogActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Loginecomp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Loginecomp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Loginecomp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Loginecomp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Loginecomp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnainv;
    private javax.swing.JButton btnlog;
    private javax.swing.JButton btnpla;
    private javax.swing.JButton btnpro;
    private javax.swing.JButton btnrec;
    private javax.swing.JButton btnvinv;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
