/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Pantallas;

/**
 *
 * @author User
 */
public class Loginadm extends javax.swing.JFrame {

    /**
     * Creates new form Loginadm
     */
    public Loginadm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnfac = new javax.swing.JButton();
        btnmen = new javax.swing.JButton();
        btnemp = new javax.swing.JButton();
        btnvinv = new javax.swing.JButton();
        btnainv = new javax.swing.JButton();
        btndom = new javax.swing.JButton();
        btnpro = new javax.swing.JButton();
        btnres = new javax.swing.JButton();
        btnrec = new javax.swing.JButton();
        btnpla = new javax.swing.JButton();
        btnlog = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LOGOPEQUEÑO.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 219, 200);

        jLabel2.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 48)); // NOI18N
        jLabel2.setText("BIENVENIDO ADMINISTRADOR");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(260, 94, 698, 95);

        btnfac.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 17)); // NOI18N
        btnfac.setText("Facturar");
        btnfac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnfacActionPerformed(evt);
            }
        });
        getContentPane().add(btnfac);
        btnfac.setBounds(1050, 240, 196, 73);

        btnmen.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 17)); // NOI18N
        btnmen.setText("Menu");
        btnmen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmenActionPerformed(evt);
            }
        });
        getContentPane().add(btnmen);
        btnmen.setBounds(740, 240, 200, 73);

        btnemp.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 17)); // NOI18N
        btnemp.setText("Empleados");
        btnemp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnempActionPerformed(evt);
            }
        });
        getContentPane().add(btnemp);
        btnemp.setBounds(600, 540, 200, 73);

        btnvinv.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 17)); // NOI18N
        btnvinv.setText("Visualizar Inventario");
        btnvinv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnvinvActionPerformed(evt);
            }
        });
        getContentPane().add(btnvinv);
        btnvinv.setBounds(90, 240, 200, 73);

        btnainv.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 17)); // NOI18N
        btnainv.setText("Agregar al Inventario");
        btnainv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnainvActionPerformed(evt);
            }
        });
        getContentPane().add(btnainv);
        btnainv.setBounds(90, 380, 200, 73);

        btndom.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 17)); // NOI18N
        btndom.setText("Domicilios");
        btndom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndomActionPerformed(evt);
            }
        });
        getContentPane().add(btndom);
        btndom.setBounds(1050, 380, 200, 73);

        btnpro.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 17)); // NOI18N
        btnpro.setText("Proveedores");
        btnpro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnproActionPerformed(evt);
            }
        });
        getContentPane().add(btnpro);
        btnpro.setBounds(270, 540, 200, 73);

        btnres.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 17)); // NOI18N
        btnres.setText("Reservaciones");
        btnres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnresActionPerformed(evt);
            }
        });
        getContentPane().add(btnres);
        btnres.setBounds(740, 380, 200, 73);

        btnrec.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 17)); // NOI18N
        btnrec.setText("Receta");
        btnrec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrecActionPerformed(evt);
            }
        });
        getContentPane().add(btnrec);
        btnrec.setBounds(420, 240, 196, 73);

        btnpla.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 17)); // NOI18N
        btnpla.setText("Platillos");
        btnpla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnplaActionPerformed(evt);
            }
        });
        getContentPane().add(btnpla);
        btnpla.setBounds(420, 380, 196, 73);

        btnlog.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 17)); // NOI18N
        btnlog.setText("cerrar sesion ");
        btnlog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlogActionPerformed(evt);
            }
        });
        getContentPane().add(btnlog);
        btnlog.setBounds(910, 540, 200, 73);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Otromas.jpg"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 0, 1355, 700);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnfacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnfacActionPerformed
        Factura obj = new Factura();
        obj.setVisible(true);    
        dispose();
    }//GEN-LAST:event_btnfacActionPerformed

    private void btnplaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnplaActionPerformed
        Platillos obj = new Platillos();
        obj.setVisible(true);    
        dispose();
    }//GEN-LAST:event_btnplaActionPerformed

    private void btnrecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrecActionPerformed
        Receta obj = new Receta();
        obj.setVisible(true);    
        dispose();
    }//GEN-LAST:event_btnrecActionPerformed

    private void btnempActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnempActionPerformed
        Empleados obj = new Empleados();
        obj.setVisible(true);    
        dispose();
    }//GEN-LAST:event_btnempActionPerformed

    private void btnvinvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnvinvActionPerformed
        Inventario2 obj = new Inventario2();
        obj.setVisible(true);    
        dispose();
    }//GEN-LAST:event_btnvinvActionPerformed

    private void btnainvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnainvActionPerformed
        Inventario obj = new Inventario();
        obj.setVisible(true);    
        dispose();
    }//GEN-LAST:event_btnainvActionPerformed

    private void btnmenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmenActionPerformed
        Menu obj = new Menu();
        obj.setVisible(true);    
        dispose();
    }//GEN-LAST:event_btnmenActionPerformed

    private void btnresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnresActionPerformed
        Reservaciones obj = new Reservaciones();
        obj.setVisible(true);    
        dispose();
    }//GEN-LAST:event_btnresActionPerformed

    private void btndomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndomActionPerformed
        Domicilios obj = new Domicilios();
        obj.setVisible(true);    
        dispose();
    }//GEN-LAST:event_btndomActionPerformed

    private void btnproActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnproActionPerformed
        Proveedores obj = new Proveedores();
        obj.setVisible(true);    
        dispose();
    }//GEN-LAST:event_btnproActionPerformed

    private void btnlogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlogActionPerformed
        Login obj = new Login();
        obj.setVisible(true);    
        dispose();
    }//GEN-LAST:event_btnlogActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Loginadm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Loginadm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Loginadm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Loginadm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Loginadm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnainv;
    private javax.swing.JButton btndom;
    private javax.swing.JButton btnemp;
    private javax.swing.JButton btnfac;
    private javax.swing.JButton btnlog;
    private javax.swing.JButton btnmen;
    private javax.swing.JButton btnpla;
    private javax.swing.JButton btnpro;
    private javax.swing.JButton btnrec;
    private javax.swing.JButton btnres;
    private javax.swing.JButton btnvinv;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
