/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Pantallas;

import ConexionBD.ConexionBD;

import Modelo.sqlReservaciones;
import java.sql.SQLException;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import com.mysql.jdbc.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
/**
 *
 * @author SAINFONET27
 */
public class Reservaciones extends javax.swing.JFrame {

    String txtmes;
    DefaultTableModel modelo = new DefaultTableModel();
    
    public Reservaciones() {
        initComponents();
        
         try {
            tableres.setModel(modelo);
            PreparedStatement ps = null;
            ResultSet rs = null;
            ConexionBD conn = new ConexionBD();
            java.sql.Connection con = conn.getConexion();

            String sql = "SELECT IdReservaciones, Hora, Fecha, NumeroMesa, Cedula1 FROM reservaciones";
            ps = con.prepareStatement(sql);
            rs = ps.executeQuery();

            ResultSetMetaData rsMd = (ResultSetMetaData) rs.getMetaData();
            int cantidadColumnas = rsMd.getColumnCount();

            modelo.addColumn("N°Reservacion");
            modelo.addColumn("Fecha");
            modelo.addColumn("Hora");
            modelo.addColumn("N°Mesa");
            modelo.addColumn("Cliente");

            while (rs.next()) {
                Object[] filas = new Object[cantidadColumnas];
                for (int i = 0; i < cantidadColumnas; i++) {
                    filas[i] = rs.getObject(i + 1);
                }
                modelo.addRow(filas);
            }

        } catch (SQLException ex) {
            System.err.println(ex.toString());
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txthor = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnguardar = new javax.swing.JButton();
        btnlimpiar = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableres = new javax.swing.JTable();
        fecha = new com.toedter.calendar.JDateChooser();
        btneliminar = new javax.swing.JButton();
        btnconsultar = new javax.swing.JButton();
        cbmes = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 48)); // NOI18N
        jLabel2.setText("RESERVACIONES");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(360, 80, 380, 47);
        getContentPane().add(jLabel4);
        jLabel4.setBounds(223, 589, 0, 0);

        txthor.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        txthor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txthorActionPerformed(evt);
            }
        });
        getContentPane().add(txthor);
        txthor.setBounds(780, 220, 180, 40);

        jLabel7.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 24)); // NOI18N
        jLabel7.setText("Hora");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(820, 170, 90, 26);

        jLabel8.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 24)); // NOI18N
        jLabel8.setText("Fecha");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(1070, 170, 80, 25);

        btnguardar.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 24)); // NOI18N
        btnguardar.setText("GUARDAR");
        btnguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguardarActionPerformed(evt);
            }
        });
        getContentPane().add(btnguardar);
        btnguardar.setBounds(840, 300, 150, 42);

        btnlimpiar.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 24)); // NOI18N
        btnlimpiar.setText("LIMPIAR");
        btnlimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlimpiarActionPerformed(evt);
            }
        });
        getContentPane().add(btnlimpiar);
        btnlimpiar.setBounds(1010, 300, 140, 42);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LOGOPEQUEÑO.png"))); // NOI18N
        getContentPane().add(jLabel9);
        jLabel9.setBounds(0, 0, 224, 200);

        jButton3.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 14)); // NOI18N
        jButton3.setText("CLIENTE");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(230, 190, 170, 90);

        tableres.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "N° Reservacion", "Fecha", "Hora", "Cliente", "N° Mesa"
            }
        ));
        tableres.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableresMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableres);
        if (tableres.getColumnModel().getColumnCount() > 0) {
            tableres.getColumnModel().getColumn(3).setResizable(false);
        }

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(170, 390, 820, 270);
        getContentPane().add(fecha);
        fecha.setBounds(1030, 220, 180, 40);

        btneliminar.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 24)); // NOI18N
        btneliminar.setText("ELIMINAR");
        btneliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminarActionPerformed(evt);
            }
        });
        getContentPane().add(btneliminar);
        btneliminar.setBounds(1020, 440, 170, 70);

        btnconsultar.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 24)); // NOI18N
        btnconsultar.setText("CONSULTAR");
        btnconsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnconsultarActionPerformed(evt);
            }
        });
        getContentPane().add(btnconsultar);
        btnconsultar.setBounds(1020, 550, 170, 70);

        cbmes.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        cbmes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4" }));
        cbmes.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Berlin Sans FB Demi", 0, 11))), "N° Mesa")); // NOI18N
        cbmes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbmesActionPerformed(evt);
            }
        });
        getContentPane().add(cbmes);
        cbmes.setBounds(520, 200, 190, 70);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Otromas.jpg"))); // NOI18N
        getContentPane().add(jLabel10);
        jLabel10.setBounds(-70, 0, 1355, 700);

        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(830, 60, 140, 110);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txthorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txthorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txthorActionPerformed

    private void btnguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguardarActionPerformed
       ConexionBD Con = new ConexionBD();
        Con.getConexion();
        txtmes= cbmes.getSelectedItem().toString();
        
        sqlReservaciones modSql = new sqlReservaciones();
        Modelo.Reservaciones mod = new Modelo.Reservaciones();
        String hora = txthor.getText();
        String dia = Integer.toString(fecha.getCalendar().get(Calendar.DAY_OF_MONTH));
        String mes = Integer.toString(fecha.getCalendar().get(Calendar.MONTH)+1);
        String year = Integer.toString(fecha.getCalendar().get(Calendar.YEAR));
        String fi=(year + "-" +mes+ "-"+dia);


        if (txthor.getText().equals("") || fi.equals("") ) {
            JOptionPane.showMessageDialog(null, "Hay campos vacios, debe llenar todos los datos");
        } else {

                        mod.setHora(txthor.getText());
                        mod.setFecha(fi);
                        mod.setNumeroMesa(txtmes);

                        
                        if (modSql.registrar(mod)) {
                            JOptionPane.showMessageDialog(null, "Registro Guardado");
                            Object[] fila = new Object[5];
                            fila[0] = txtmes;
                            fila[1] = txthor.getText();
                            fila[2] = fi;
                            modelo.addRow(fila);
                            limpiar();
                            
                        } else {
                            JOptionPane.showMessageDialog(null, "Error al Guardar");
                            
                        }
            }       
    }//GEN-LAST:event_btnguardarActionPerformed

    private void btnlimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlimpiarActionPerformed
        limpiar();
      
    }//GEN-LAST:event_btnlimpiarActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btneliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminarActionPerformed
         try{
        String id = tableres.getValueAt(tableres.getSelectedRow(), 0) .toString();
        ConexionBD Con = new ConexionBD();
        Con.getConexion();
        String SQL = "DELETE FROM reservaciones WHERE IdReservaciones='"+id+"'";
        Con.sentencia.execute(SQL);
        JOptionPane.showMessageDialog(null, "¡El registro fué eliminado!");
        Con.DesconectarBD();
        } catch (SQLException ex) {
	Logger.getLogger(Reservaciones.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btneliminarActionPerformed

    private void btnconsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnconsultarActionPerformed
      
    }//GEN-LAST:event_btnconsultarActionPerformed

    private void cbmesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbmesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbmesActionPerformed

    private void tableresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableresMouseClicked
         PreparedStatement ps = null;
        ResultSet rs = null;
        String dia = Integer.toString(fecha.getCalendar().get(Calendar.DAY_OF_MONTH));
        String mes = Integer.toString(fecha.getCalendar().get(Calendar.MONTH)+1);
        String year = Integer.toString(fecha.getCalendar().get(Calendar.YEAR));
        String fi=(year + "-" +mes+ "-"+dia);
        try {
            ConexionBD objCon = new ConexionBD();
            Connection conn = (Connection) objCon.getConexion();

            int Fila = tableres.getSelectedRow();
            String cedula = tableres.getValueAt(Fila, 0).toString();

            ps = conn.prepareStatement("SELECT Hora, Fecha, NumeroMesa, Cedula1 FROM reservaciones WHERE IdReservaciones=?");
            ps.setString(1, cedula);
            rs = ps.executeQuery();

            while (rs.next()) {
                cbmes.setSelectedItem(rs.getString("N°Mesa"));
                txthor.setText(rs.getString("Hora"));

            }
        } catch (SQLException ex) {
            System.out.println(ex.toString());
        }
    }//GEN-LAST:event_tableresMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Reservaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Reservaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Reservaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Reservaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Reservaciones().setVisible(true);
            }
        });
    }
public void limpiar()
    {
        txthor.setText(null);

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnconsultar;
    private javax.swing.JButton btneliminar;
    private javax.swing.JButton btnguardar;
    private javax.swing.JButton btnlimpiar;
    public javax.swing.JComboBox<String> cbmes;
    public com.toedter.calendar.JDateChooser fecha;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable tableres;
    public javax.swing.JTextField txthor;
    // End of variables declaration//GEN-END:variables
}
