/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Pantallas;

import ConexionBD.ConexionBD;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author SAINFONET28
 */
public class Inventario extends javax.swing.JFrame {

    /**
     * Creates new form Inventario
     */
    public Inventario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtpro = new javax.swing.JTextField();
        txtcant = new javax.swing.JTextField();
        txtnom = new javax.swing.JTextField();
        txtuni = new javax.swing.JTextField();
        txtvuni = new javax.swing.JTextField();
        btnguardar = new javax.swing.JButton();
        btnlimpiar = new javax.swing.JButton();
        btnvisualizar = new javax.swing.JButton();
        txtrpro = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 48)); // NOI18N
        jLabel1.setText("INVENTARIO");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(470, 40, 300, 90);

        jLabel2.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 24)); // NOI18N
        jLabel2.setText("Referencia de producto");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(280, 200, 270, 30);

        jLabel3.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 24)); // NOI18N
        jLabel3.setText("Nombre");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(280, 260, 260, 28);

        jLabel4.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 24)); // NOI18N
        jLabel4.setText("Unidad");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(280, 380, 280, 28);

        jLabel5.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 24)); // NOI18N
        jLabel5.setText("Cantidad");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(280, 320, 280, 28);

        jLabel6.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 24)); // NOI18N
        jLabel6.setText("Valor unitario");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(280, 440, 280, 28);

        txtpro.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        txtpro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtproActionPerformed(evt);
            }
        });
        getContentPane().add(txtpro);
        txtpro.setBounds(630, 490, 270, 50);

        txtcant.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        txtcant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcantActionPerformed(evt);
            }
        });
        getContentPane().add(txtcant);
        txtcant.setBounds(630, 310, 270, 50);

        txtnom.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        txtnom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnomActionPerformed(evt);
            }
        });
        getContentPane().add(txtnom);
        txtnom.setBounds(630, 250, 270, 50);

        txtuni.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        txtuni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtuniActionPerformed(evt);
            }
        });
        getContentPane().add(txtuni);
        txtuni.setBounds(630, 370, 270, 50);

        txtvuni.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        txtvuni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtvuniActionPerformed(evt);
            }
        });
        getContentPane().add(txtvuni);
        txtvuni.setBounds(630, 430, 270, 50);

        btnguardar.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 24)); // NOI18N
        btnguardar.setText("GUARDAR");
        btnguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguardarActionPerformed(evt);
            }
        });
        getContentPane().add(btnguardar);
        btnguardar.setBounds(570, 590, 180, 70);

        btnlimpiar.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 24)); // NOI18N
        btnlimpiar.setText("LIMPIAR");
        btnlimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlimpiarActionPerformed(evt);
            }
        });
        getContentPane().add(btnlimpiar);
        btnlimpiar.setBounds(250, 590, 180, 70);

        btnvisualizar.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 24)); // NOI18N
        btnvisualizar.setText("VISUALIZAR");
        btnvisualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnvisualizarActionPerformed(evt);
            }
        });
        getContentPane().add(btnvisualizar);
        btnvisualizar.setBounds(870, 590, 180, 70);

        txtrpro.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        txtrpro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtrproActionPerformed(evt);
            }
        });
        getContentPane().add(txtrpro);
        txtrpro.setBounds(630, 190, 270, 50);

        jLabel7.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 24)); // NOI18N
        jLabel7.setText("Proveedor");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(280, 500, 270, 28);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondo.jpg"))); // NOI18N
        getContentPane().add(jLabel8);
        jLabel8.setBounds(206, 20, 0, 0);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LOGOPEQUEÑO.png"))); // NOI18N
        getContentPane().add(jLabel9);
        jLabel9.setBounds(0, 0, 200, 212);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Otromas.jpg"))); // NOI18N
        getContentPane().add(jLabel11);
        jLabel11.setBounds(0, 0, 1360, 700);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtproActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtproActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtproActionPerformed

    private void txtcantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcantActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcantActionPerformed

    private void txtnomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnomActionPerformed

    private void txtuniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtuniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtuniActionPerformed

    private void txtvuniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtvuniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtvuniActionPerformed

    private void btnguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguardarActionPerformed
        ConexionBD Con = new ConexionBD();
        Con.getConexion();
        String refer = txtrpro.getText();
        String nom = txtnom.getText();
        String cant = txtcant.getText();
        String uni = txtuni.getText();
        String val = txtvuni.getText();
        String pro = txtpro.getText();
        if (!refer.isEmpty()){
            if (!nom.isEmpty()) {
                if (!cant.isEmpty()) {
                    if (!uni.isEmpty()) {
                        if (!val.isEmpty()) {
                            if (!pro.isEmpty()) {
                                    try {
                                        String SQL = "INSERT INTO inventario"
                                                +"(ReferenciaProducto,NombreIngrediente,Cantidad,Unidad,ValorUnitario,IdProveedor)"
                                                +" VALUES "
                                                +"('"+refer+"','"+nom+"','"+cant+"','"+uni+"','"+val+"','"+pro+"');";
                                        Con.sentencia.execute(SQL);
                                        JOptionPane.showMessageDialog(null, "¡Los datos fueron guardados con exito!");
                                    } catch (SQLException ex) {
                                        Logger.getLogger(Inventario.class.getName()).log(Level.SEVERE,null, ex);
                                    }
                                } else {
                                    JOptionPane.showMessageDialog(null, "Por favor ingrese el proveedor del producto");
                                }
                            } else {
                                JOptionPane.showMessageDialog(null, "Por favor ingrese el valor unitario del producto");
                            }
                        } else {
                            JOptionPane.showMessageDialog(null, "Por favor la unidad del producto");
                        }
                    } else {
                        JOptionPane.showMessageDialog(null, "Por favor ingrese la cantidad");
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Por favor ingrese el nombre del producto");
                }
            } else {
                JOptionPane.showMessageDialog(null, "Por favor ingrese la referencia del producto");
            }
        Con.DesconectarBD();
    }//GEN-LAST:event_btnguardarActionPerformed

    private void btnvisualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnvisualizarActionPerformed
        Inventario2 obj = new Inventario2();
        obj.setVisible(true);    
        dispose();
    }//GEN-LAST:event_btnvisualizarActionPerformed

    private void txtrproActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtrproActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtrproActionPerformed

    private void btnlimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlimpiarActionPerformed
        txtrpro.setText("");
        txtnom.setText("");
        txtcant.setText("");
        txtuni.setText("");
        txtvuni.setText("");
        txtpro.setText("");
    }//GEN-LAST:event_btnlimpiarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inventario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnguardar;
    private javax.swing.JButton btnlimpiar;
    private javax.swing.JButton btnvisualizar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtcant;
    private javax.swing.JTextField txtnom;
    private javax.swing.JTextField txtpro;
    private javax.swing.JTextField txtrpro;
    private javax.swing.JTextField txtuni;
    private javax.swing.JTextField txtvuni;
    // End of variables declaration//GEN-END:variables
}
