/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Pantallas;

import ConexionBD.ConexionBD;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author SAINFONET28
 */
public class Platillos extends javax.swing.JFrame {

    /**
     * Creates new form Platillos
     */
    public Platillos() {
        initComponents();
        Crear_Modelo();
    }
    public static Platillos prin;
        private Object JOptionpane;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtnom = new javax.swing.JTextField();
        txtpor = new javax.swing.JTextField();
        txtpre = new javax.swing.JTextField();
        txtpla = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablepla = new javax.swing.JTable();
        btnguardar = new javax.swing.JButton();
        btnlimpiar = new javax.swing.JButton();
        btnconsultar = new javax.swing.JButton();
        btnactualizar = new javax.swing.JButton();
        btneliminar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtcat = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 48)); // NOI18N
        jLabel1.setText("PLATILLOS");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(380, 30, 270, 90);

        jLabel2.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 24)); // NOI18N
        jLabel2.setText("N° Platillo");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(280, 170, 120, 22);

        jLabel3.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 24)); // NOI18N
        jLabel3.setText("Precio");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(280, 370, 71, 22);

        jLabel4.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 24)); // NOI18N
        jLabel4.setText("Categoria");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(280, 320, 120, 22);

        jLabel5.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 24)); // NOI18N
        jLabel5.setText("Porciones");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(280, 270, 120, 22);

        jLabel6.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 24)); // NOI18N
        jLabel6.setText("Nombre");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(280, 220, 100, 22);
        getContentPane().add(txtnom);
        txtnom.setBounds(470, 212, 230, 40);
        getContentPane().add(txtpor);
        txtpor.setBounds(470, 262, 230, 40);

        txtpre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpreActionPerformed(evt);
            }
        });
        getContentPane().add(txtpre);
        txtpre.setBounds(470, 362, 230, 40);

        txtpla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtplaActionPerformed(evt);
            }
        });
        getContentPane().add(txtpla);
        txtpla.setBounds(470, 162, 230, 40);

        tablepla.setFont(new java.awt.Font("Elephant", 0, 11)); // NOI18N
        tablepla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "N° Platillo", "Nombre", "Porciones", "Categoria", "Precio"
            }
        ));
        jScrollPane1.setViewportView(tablepla);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(60, 430, 730, 240);

        btnguardar.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 24)); // NOI18N
        btnguardar.setText("GUARDAR");
        btnguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguardarActionPerformed(evt);
            }
        });
        getContentPane().add(btnguardar);
        btnguardar.setBounds(850, 150, 230, 80);

        btnlimpiar.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 24)); // NOI18N
        btnlimpiar.setText("LIMPIAR");
        btnlimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlimpiarActionPerformed(evt);
            }
        });
        getContentPane().add(btnlimpiar);
        btnlimpiar.setBounds(850, 250, 230, 80);

        btnconsultar.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 24)); // NOI18N
        btnconsultar.setText("CONSULTAR");
        btnconsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnconsultarActionPerformed(evt);
            }
        });
        getContentPane().add(btnconsultar);
        btnconsultar.setBounds(840, 510, 230, 60);

        btnactualizar.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 24)); // NOI18N
        btnactualizar.setText("ACTUALIZAR");
        btnactualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnactualizarActionPerformed(evt);
            }
        });
        getContentPane().add(btnactualizar);
        btnactualizar.setBounds(840, 440, 230, 60);

        btneliminar.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 24)); // NOI18N
        btneliminar.setText("ELIMINAR");
        btneliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminarActionPerformed(evt);
            }
        });
        getContentPane().add(btneliminar);
        btneliminar.setBounds(840, 580, 230, 60);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LOGOPEQUEÑO.png"))); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(0, 0, 227, 200);

        txtcat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcatActionPerformed(evt);
            }
        });
        getContentPane().add(txtcat);
        txtcat.setBounds(470, 310, 230, 40);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Otromas.jpg"))); // NOI18N
        getContentPane().add(jLabel9);
        jLabel9.setBounds(0, 0, 1355, 700);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnconsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnconsultarActionPerformed
        Consultar();
    }//GEN-LAST:event_btnconsultarActionPerformed

    private void btnactualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnactualizarActionPerformed
        String nom = tablepla.getValueAt(tablepla.getSelectedRow(), 0).toString();
        String por = tablepla.getValueAt(tablepla.getSelectedRow(), 1).toString();
        String cat = tablepla.getValueAt(tablepla.getSelectedRow(), 2).toString();
        String pre = tablepla.getValueAt(tablepla.getSelectedRow(), 3).toString();
        ActualizarPlat Act = new ActualizarPlat (null, true);
        Act.atxtnom.setText(nom);
        Act.atxtpor.setText(por);
        Act.atxtcat.setText(cat);
        Act.atxtpre.setText(pre);
        Act.setVisible(true);
    }//GEN-LAST:event_btnactualizarActionPerformed

    private void btneliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminarActionPerformed
        try{
        String nom = tablepla.getValueAt(tablepla.getSelectedRow(), 0) .toString();
        ConexionBD Con = new ConexionBD();
        Con.getConexion();
        String SQL = "DELETE FROM platillos WHERE NombrePlatillo='"+nom+"'";
        Con.sentencia.execute(SQL);
        JOptionPane.showMessageDialog(null, "¡El registro fué eliminado!");
        Con.DesconectarBD();
        } catch (SQLException ex) {
	Logger.getLogger(Platillos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btneliminarActionPerformed

    private void txtpreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpreActionPerformed

    private void txtplaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtplaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtplaActionPerformed

    private void txtcatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcatActionPerformed

    private void btnlimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlimpiarActionPerformed
    txtnom.setText("");
    txtpor.setText("");
    txtcat.setText("");
    txtpre.setText("");

    }//GEN-LAST:event_btnlimpiarActionPerformed

    private void btnguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguardarActionPerformed
        ConexionBD Con = new ConexionBD();
        Con.getConexion();
        String nom = txtnom.getText();
        String por = txtpor.getText();
        String cat = txtcat.getText();
        String pre = txtpre.getText();

        if (!nom.isEmpty()){
            if (!por.isEmpty()) {
                if (!cat.isEmpty()) {
                    if (!pre.isEmpty()) {
                       
                                try {
                                        String SQL = "INSERT INTO platillos"
                                                +"(NombrePlatillo,Porciones,Categoria,PrecioPlatillo)"
                                                +" VALUES "
                                                +"('"+nom+"','"+por+"','"+cat+"','"+pre+"');";
                                        Con.sentencia.execute(SQL);
                                        JOptionPane.showMessageDialog(null, "¡Los datos fueron guardados con exito!");
                                    } catch (SQLException ex) {
                                        Logger.getLogger(Empleados.class.getName()).log(Level.SEVERE,null, ex);
                                    }
                                } else {
                                    JOptionPane.showMessageDialog(null, "Por favor ingrese el precio del platillo");
                                }
                            } else {
                                JOptionPane.showMessageDialog(null, "Por favor ingrese la categoria del platillo");
                            }
                        } else {
                            JOptionPane.showMessageDialog(null, "Por favor ingrese la porcion del platilo");
                        }
                    } else {
                        JOptionPane.showMessageDialog(null, "Por favor ingrese el nombred el platillo");
                    }
             
        
        Con.DesconectarBD();
    }//GEN-LAST:event_btnguardarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Platillos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Platillos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Platillos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Platillos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Platillos().setVisible(true);
            }
        });
    }
DefaultTableModel modelo;
      private void Crear_Modelo() {
        try{
            modelo = (new DefaultTableModel(
                    null, new String[]{
                      "N°Platillo" ," NombrePlatillo", "Porciones", "Categoria",
                      "PrecioPlatillo"}) {
                     Class[] types = new Class[]{
                     java.lang.String.class,java.lang.String.class,
                     java.lang.String.class,java.lang.String.class,
                     java.lang.String.class,java.lang.String.class,
                     java.lang.String.class,java.lang.String.class,
                     java.lang.String.class,java.lang.String.class,
                    };
                    boolean[] canEdit = new boolean[]{
                        false, false, false, false
                    };
                    public Class getColumnClass(int columnIndex){
                        return types[columnIndex];
                    }
                    public boolean isCellEditable(int rowIndex, int colIndex){
                        return canEdit[colIndex];
                    }
            });
            tablepla.setModel(modelo);
            
            } catch (Exception e){
                JOptionPane.showMessageDialog(null, e.toString() + "Error");
                }
        }
      private void Consultar(){
          try{
            int i=0; Object ob[]=null;
            ConexionBD Con = new ConexionBD();
            Con.getConexion();
            String SQL = "SELECT * FROM platillos";
            Con.resultado = Con.sentencia.executeQuery(SQL);
            while (Con.resultado.next()){
                modelo.addRow(ob);
                modelo.setValueAt(Con.resultado.getString("NombrePlatillo"), i, 0);
                modelo.setValueAt(Con.resultado.getString("Porciones"), i, 1);
                modelo.setValueAt(Con.resultado.getString("Categoria"), i, 2);
                modelo.setValueAt(Con.resultado.getString("PrecioPlatillo"), i, 3);
                i++;
            }
            Con.DesconectarBD();
        } catch (SQLException ex){
            Logger.getLogger(Platillos.class .getName()).log(Level.SEVERE, null, ex);
        }
      }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnactualizar;
    private javax.swing.JButton btnconsultar;
    private javax.swing.JButton btneliminar;
    private javax.swing.JButton btnguardar;
    private javax.swing.JButton btnlimpiar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablepla;
    private javax.swing.JTextField txtcat;
    private javax.swing.JTextField txtnom;
    private javax.swing.JTextField txtpla;
    private javax.swing.JTextField txtpor;
    private javax.swing.JTextField txtpre;
    // End of variables declaration//GEN-END:variables
}
